-- Criação da tabela Usuario (tabela base para Cliente e Funcionario com estratégia JOINED)
CREATE TABLE usuario (
    cpf VARCHAR(255) PRIMARY KEY,
    nome VARCHAR(100) NOT NULL
);

-- Criação da tabela Cliente
CREATE TABLE cliente (
    cpf VARCHAR(255) PRIMARY KEY,
    -- Colunas adicionais específicas de Cliente, se houver.
    -- Aqui, a PK é também uma FK para a tabela usuario, conforme InheritanceType.JOINED
    FOREIGN KEY (cpf) REFERENCES usuario(cpf)
);

-- Criação da tabela Funcionario
CREATE TABLE funcionario (
    cpf VARCHAR(255) PRIMARY KEY,
    matricula VARCHAR(255) UNIQUE,
    -- Colunas adicionais específicas de Funcionario, se houver.
    -- Aqui, a PK é também uma FK para a tabela usuario, conforme InheritanceType.JOINED
    FOREIGN KEY (cpf) REFERENCES usuario(cpf)
);

-- Criação da tabela Pet
CREATE TABLE pet (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    especie VARCHAR(255),
    raca VARCHAR(255),
    porte VARCHAR(255),
    cliente_id VARCHAR(255) NOT NULL,
    FOREIGN KEY (cliente_id) REFERENCES cliente(cpf)
);

-- Criação da tabela Servico
CREATE TABLE servico (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo VARCHAR(255) NOT NULL,
    preco DECIMAL(10, 2) NOT NULL
);

-- Criação da tabela Atendimento
CREATE TABLE atendimento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_hora TIMESTAMP NOT NULL,
    status VARCHAR(255) NOT NULL,
    confirmado BOOLEAN,
    cliente_id VARCHAR(255) NOT NULL,
    pet_id BIGINT NOT NULL,
    funcionario_id VARCHAR(255) NOT NULL,
    servico_id BIGINT NOT NULL,
    FOREIGN KEY (cliente_id) REFERENCES cliente(cpf),
    FOREIGN KEY (pet_id) REFERENCES pet(id),
    FOREIGN KEY (funcionario_id) REFERENCES funcionario(cpf),
    FOREIGN KEY (servico_id) REFERENCES servico(id)
);

-- Criação da tabela HorarioDisponivel
CREATE TABLE horario_disponivel (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    funcionario_cpf VARCHAR(255) NOT NULL,
    servico_id BIGINT, -- Pode ser nulo se o slot for genérico para o funcionário
    data_hora_inicio TIMESTAMP NOT NULL,
    data_hora_fim TIMESTAMP NOT NULL,
    ocupado BOOLEAN NOT NULL DEFAULT FALSE, -- Por padrão, o slot começa como não ocupado

    FOREIGN KEY (funcionario_cpf) REFERENCES funcionario(cpf),
    FOREIGN KEY (servico_id) REFERENCES servico(id)
);

-- Inserindo Usuários (base para Cliente e Funcionário)
INSERT INTO USUARIO (cpf, nome) VALUES ('11122233344', 'João Cliente');
INSERT INTO USUARIO (cpf, nome) VALUES ('55566677788', 'Maria Funcionária');
INSERT INTO USUARIO (cpf, nome) VALUES ('99988877766', 'Dr. Animal');

-- Inserindo Clientes
INSERT INTO CLIENTE (cpf) VALUES ('11122233344');

-- Inserindo Funcionários
INSERT INTO FUNCIONARIO (cpf, matricula) VALUES ('55566677788', 'FNC001');
INSERT INTO FUNCIONARIO (cpf, matricula) VALUES ('99988877766', 'VET001');

-- Inserindo Pets para o Cliente '11122233344' (João Cliente)
INSERT INTO PET (nome, especie, raca, porte, cliente_id) VALUES ('Rex', 'Cachorro', 'Labrador', 'Grande', '11122233344');
INSERT INTO PET (nome, especie, raca, porte, cliente_id) VALUES ('Mia', 'Gato', 'Siamês', 'Pequeno', '11122233344');

-- Inserindo Serviços
INSERT INTO SERVICO (tipo, preco) VALUES ('Banho e Tosa', 75.00);
INSERT INTO SERVICO (tipo, preco) VALUES ('Consulta Veterinária', 120.00);
INSERT INTO SERVICO (tipo, preco) VALUES ('Vacinação V8', 90.00);

INSERT INTO HORARIO_DISPONIVEL (funcionario_cpf, servico_id, data_hora_inicio, data_hora_fim, ocupado)
VALUES ('55566677788', (SELECT id FROM SERVICO WHERE tipo = 'Banho e Tosa'), '2025-07-13 09:00:00', '2025-07-13 10:00:00', FALSE);

-- Horário para Dr. Animal, para Consulta Veterinária
INSERT INTO HORARIO_DISPONIVEL (funcionario_cpf, servico_id, data_hora_inicio, data_hora_fim, ocupado)
VALUES ('99988877766', (SELECT id FROM SERVICO WHERE tipo = 'Consulta Veterinária'), '2025-07-13 10:00:00', '2025-07-13 11:00:00', FALSE);

-- Outro Horário para Maria Funcionária, genérico (sem serviço específico)
INSERT INTO HORARIO_DISPONIVEL (funcionario_cpf, servico_id, data_hora_inicio, data_hora_fim, ocupado)
VALUES ('55566677788', NULL, '2025-07-13 11:00:00', '2025-07-13 12:00:00', FALSE);

-- Um horário que já está ocupado (para testar a validação/não aparecer na lista do cliente)
INSERT INTO HORARIO_DISPONIVEL (funcionario_cpf, servico_id, data_hora_inicio, data_hora_fim, ocupado)
VALUES ('99988877766', (SELECT id FROM SERVICO WHERE tipo = 'Vacinação V8'), '2025-07-13 14:00:00', '2025-07-13 15:00:00', TRUE);